FROM node:18-alpine
WORKDIR /opt/app
COPY . .

ARG URL_SUPABASE
ARG TOKEN_SUPABASE

ENV SUPABASE_URL=URL_SUPABASE
ENV SUPABASE_TOKEN=TOKEN_SUPABASE

RUN npm install
# ENV HOST 0.0.0.0
EXPOSE 8080
CMD [ "npm", "start"]
