name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          PROJECT_ID: boot-camp-gdsc
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/boot-camp-gdsc/harijs:latest
          build-args: |
            HTTP_PORT=8080
            URL_SUPABASE=${{ secrets.SUPABASE_URL }}
            TOKEN_SUPABASE=${{ secrets.SUPABASE_TOKEN }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/boot-camp-gdsc/harijs:latest
          service: harijs-prod
          region: asia-southeast2
          platform: managed
          allow-unauthenticated: true
          port: 8080
          timeout: 3m
          env_vars: |
              PORT=8080
              SUPABASE_URL=${{ secrets.SUPABASE_URL }}
              SUPABASE_TOKEN=${{ secrets.SUPABASE_TOKEN }}
